using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Text;
using System.Text.Json;

using Microsoft.Extensions.FileProviders;

namespace InteropTypes.IO
{
    public class ArchiveFileInfo
        : IFileInfo
        , IServiceProvider
    {
        public ArchiveFileInfo(SharpCompress.Archives.IArchiveEntry entry)
        {
            _Entry = entry;
        }        

        private readonly SharpCompress.Archives.IArchiveEntry _Entry;

        public bool Exists => true;

        public long Length => _Entry.Size;

        public string PhysicalPath => _Entry.Key;

        public string Name => System.IO.Path.GetFileName(_Entry.Key);

        public DateTimeOffset LastModified => _Entry.LastModifiedTime ?? DateTimeOffset.MinValue;

        public bool IsDirectory => _Entry.IsDirectory;

        public Stream CreateReadStream()
        {
            return _Entry.OpenEntryStream();
        }


        public bool TryGetCommentJsonProperty(string key, out string value)
        {
            if (_Entry is SharpCompress.Archives.Zip.ZipArchiveEntry zipEntry) // if zip entry has json generated by directory commander...
            {
                if (!string.IsNullOrWhiteSpace(zipEntry.Comment))
                {
                    value  = _GetJsonStringProperty(zipEntry.Comment, key);
                    if (value != null) return true;                    
                }
            }            

            value = null;
            return false;
        }

        private string _GetJsonStringProperty(string json, string key)
        {
            key = "\"" + key + "\":";

            var idx = json.IndexOf(key);
            if (idx < 0) return null;
            json = json.Substring(idx + key.Length);

            idx = json.IndexOf("\"");
            if (idx < 0) return null;
            json = json.Substring(idx + 1);

            idx = json.IndexOf("\"");
            if (idx < 0) return null;
            json = json.Substring(0, idx);

            return json;
        }

        public object GetService(Type serviceType)
        {
            if (serviceType == typeof(SharpCompress.Archives.IArchiveEntry)) return _Entry;

            if (_Entry is SharpCompress.Archives.Zip.ZipArchiveEntry zipEntry)
            {
                try
                {
                    if (serviceType == typeof(string)) return zipEntry.Comment;                    

                    if (serviceType == typeof(JsonDocument))
                    {
                        return string.IsNullOrWhiteSpace(zipEntry.Comment)
                            ? null
                            : (object)JsonDocument.Parse(zipEntry.Comment);
                    }
                }
                catch { }
            }            

            return null;
        }
    }
}
