name: Publish ALL packages to Nuget

on: workflow_dispatch
    
jobs:
  build_job:  
    uses: ./.github/workflows/BuildPackages.yml
  publish_job:
    needs: build_job
    runs-on: ubuntu-latest        
    steps:   

    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        name: nuget-packages

#    - name: Push to NuGet
#      run: dotnet nuget push "*.nupkg" --api-key ${{secrets.InteropTypes_PublishToNuget}} --source https://api.nuget.org/v3/index.json

    - name: Push to NuGet
      run: dotnet nuget push "InteropTypes.Tensors.*.nupkg" --api-key ${{secrets.InteropTypes_PublishToNuget}} --source https://api.nuget.org/v3/index.json

    - name: Push to NuGet
      run: dotnet nuget push "InteropTypes.Graphics.Drawing.*.nupkg" --api-key ${{secrets.InteropTypes_PublishToNuget}} --source https://api.nuget.org/v3/index.json

    - name: Push to NuGet
      run: dotnet nuget push "InteropTypes.Graphics.Bitmaps.*.nupkg" --api-key ${{secrets.InteropTypes_PublishToNuget}} --source https://api.nuget.org/v3/index.json

    - name: Push to NuGet
      run: dotnet nuget push "InteropTypes.Graphics.Backends.ImageSharp.*.nupkg" --api-key ${{secrets.InteropTypes_PublishToNuget}} --source https://api.nuget.org/v3/index.json

    - name: Push to NuGet
      run: dotnet nuget push "InteropTypes.Graphics.Backends.GDI.*.nupkg" --api-key ${{secrets.InteropTypes_PublishToNuget}} --source https://api.nuget.org/v3/index.json

    - name: Push to NuGet
      run: dotnet nuget push "InteropTypes.Graphics.Backends.MonoGame.*.nupkg" --api-key ${{secrets.InteropTypes_PublishToNuget}} --source https://api.nuget.org/v3/index.json

    - name: Push to NuGet
      run: dotnet nuget push "InteropTypes.Graphics.Backends.WPF.*.nupkg" --api-key ${{secrets.InteropTypes_PublishToNuget}} --source https://api.nuget.org/v3/index.json

    - name: Push to NuGet
      run: dotnet nuget push "InteropTypes.Graphics.Backends.GLTF.*.nupkg" --api-key ${{secrets.InteropTypes_PublishToNuget}} --source https://api.nuget.org/v3/index.json

    - name: Push to NuGet
      run: dotnet nuget push "InteropTypes.Graphics.Backends.Avalonia.*.nupkg" --api-key ${{secrets.InteropTypes_PublishToNuget}} --source https://api.nuget.org/v3/index.json

    - name: Push to NuGet
      run: dotnet nuget push "InteropTypes.Graphics.Backends.SpanBitmap.*.nupkg" --api-key ${{secrets.InteropTypes_PublishToNuget}} --source https://api.nuget.org/v3/index.json

    - name: Push to NuGet
      run: dotnet nuget push "InteropTypes.Codecs.STB.*.nupkg" --api-key ${{secrets.InteropTypes_PublishToNuget}} --source https://api.nuget.org/v3/index.json

    - name: Push to NuGet
      run: dotnet nuget push "InteropTypes.Codecs.MJPEG.*.nupkg" --api-key ${{secrets.InteropTypes_PublishToNuget}} --source https://api.nuget.org/v3/index.json

    - name: Push to NuGet
      run: dotnet nuget push "InteropTypes.Crypto.*.nupkg" --api-key ${{secrets.InteropTypes_PublishToNuget}} --source https://api.nuget.org/v3/index.json

    - name: Push to NuGet
      run: dotnet nuget push "InteropTypes.IO.FilePreviews.*.nupkg" --api-key ${{secrets.InteropTypes_PublishToNuget}} --source https://api.nuget.org/v3/index.json
