name: Publish SOURCE packages to Nuget

on: workflow_dispatch
    
jobs:
  build:  
    uses: ./.github/workflows/BuildPackages.yml
  publish:
    needs: build
    runs-on: ubuntu-latest        
    steps:   

    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        name: nuget-packages

    - name: Push to NuGet
      run: dotnet nuget push "*.Sources.*.nupkg" --api-key ${{secrets.InteropTypes_PublishToNuget}} --source https://api.nuget.org/v3/index.json